filebeat:
  inputs:
    - type: log
      enabled: true
      paths:
       - /var/log/nginx/acces.log
       - /var/log/nginx/error.log
output:
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
    
